# Generated by Django 3.1.4 on 2021-12-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(choices=[('Istanbul', 'Istanbul'), ('Ankara', 'Ankara')], max_length=200, null=True),
        ),
    ]
