# Generated by Django 3.1.4 on 2021-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211216_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticketsell',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(choices=[('Today', 'Today'), ('NextWeek', 'NextWeek')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
