# Generated by Django 3.1.4 on 2022-01-01 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0011_auto_20220101_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventTicketSell',
            new_name='Booking',
        ),
    ]
