# Generated by Django 3.1.4 on 2022-01-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20220101_1716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket_Class',
            new_name='Ticket',
        ),
    ]
