# Generated by Django 3.1.4 on 2022-01-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
