# Generated by Django 3.1.4 on 2022-01-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20220106_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticketname',
        ),
    ]
