# Generated by Django 4.0.1 on 2022-01-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211215_1934'),
        ('events', '0020_remove_ticket_ticketname'),
    ]

    operations = [
    ]
