# Generated by Django 3.1.4 on 2022-01-07 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('country', models.CharField(choices=[('Turkey', 'Turkey')], max_length=200, null=True)),
                ('city', models.CharField(choices=[('Istanbul', 'Istanbul'), ('Ankara', 'Ankara'), ('İzmir', 'İzmir'), ('Antalya', 'Antalya')], max_length=200, null=True)),
                ('ZIP', models.IntegerField(max_length=100, null=True)),
                ('addressowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
