# Generated by Django 4.0.1 on 2022-01-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_address_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ZIP',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
