# Generated by Django 3.1.4 on 2022-01-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220126_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='wallet_money',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
